require 'rubygems'
require 'rake'
require 'date'

#############################################################################
#
# Standard tasks
#
#############################################################################

require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << "test/" << "c:/git/Faker.Net/Faker.Net/bin/Debug/sugar.dll"
  t.ruby_opts << "-rhelper"
  t.test_files = FileList['test/test*.rb']
  t.verbose = true
end

task :default => :test


